
logging:
  level:
    org.springframework.web: INFO

spring:
  application:
    name: ncr-flight-api
  groovy:
    template:
      configuration:
        cache-templates: false
        #resource-loader-path: /templates

ncr:
  flight:
    db:
      driver: com.mysql.cj.jdbc.Driver
      connection: jdbc:mysql://db.ncr/flight
  records:
    db:
      driver: com.mysql.cj.jdbc.Driver
      connection: jdbc:mysql://db.ncr/flight

