
logging:
  level:
    org.springframework.web: INFO

spring:
  application:
    name: ncr-flight-api
  groovy:
    template:
      configuration:
        auto-indent: true
        cache-templates: false
        auto-new-line: true
        resource-loader-path: templates




ncr:
  db:
    username:
    password:
    driver: com.cj.jdbc.Driver
    connection: jdbc:mysql://sql.morsecode-inc.com/ncrdev

